# picked up by org.springframework.boot:spring-boot-docker-compose
services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment: # defined in <root>/secrets/secrets.properties
      - 'POSTGRES_DB=${db__postgres__dbname}'
      - 'POSTGRES_PASSWORD=${db__postgres__password}'
      - 'POSTGRES_USER=${db__postgres__user}'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      # - '5432:5432'  # if not having a local/nonDocker postgresql running use  '5432:5432'
      - '15432:5432'   # if     having a local/nonDocker postgresql running use '15432:5432'
